// Generated by CoffeeScript 1.9.3
(function() {
  var DQ_ID3_Visualizer,
    slice = [].slice;

  DQ_ID3_Visualizer = {
    attributes: [],
    training_data: [],
    test_data: [],
    init: function() {
      return $.ajax({
        method: 'GET',
        url: 'file://data/adult.json',
        dataType: 'json',
        success: function() {
          var x;
          x = 1 <= arguments.length ? slice.call(arguments, 0) : [];
          return console.log(x);
        }
      });
    }
  };

  DQ_ID3_Visualizer.init();

}).call(this);
